apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_PORT: '5432'
  POSTGRES_HOST: postgres-service
